### ISSUE TITLE
Behaviour of block.number on eth_call is incorrect

### ISSUE THREAD

**Issue by guanzhenxing** [OffchainLabs/arbitrum#1005]
Problem: When using block.number in Solidity code, sometimes it uses the blockNumber of L1 and sometimes it uses the blockNumber of L2. (See screenshot and code for detailed instructions).

Requirement: What exactly is the behaviour of block.number? How to ensure that it always returns the L1 or L2 blockNumber in the contract.

This is my test code: https://github.com/guanzhenxing/arbiturm-test

The error happened in the getBlockDelta() method:

```solidity
    function getBlockDelta() public view returns (uint){
        uint currentBlockNumber = getBlockNumber();
        State storage state = userState[msg.sender];
        uint delta = sub(currentBlockNumber, state.blockNumber);

        return delta;
    }

    function getBlockNumber() public view returns (uint256){
        return block.number;
    }

    function sub(uint256 a, uint256 b) internal pure returns (uint256) {
        require(b <= a, "SafeMath: subtraction overflow");
        return a - b;
    }
```

![image](https://user-images.githubusercontent.com/3087325/118068009-2f200b80-b3d4-11eb-91af-6339cb7eb1dd.png)

**Comment by DZGoldman** [comment]
Expected behavior is the Arbitrum block number is returned by `ArbSys.arbBlockNumber()` and included in transaction receipts; an L1-ish block number is returned by `block.number` in solidity (as described [here](
https://developer.offchainlabs.com/docs/time_in_arbitrum)).  That seems consistent w/ what you describe seeing, so closing unless/until some inconsistency is reproducible
