### ISSUE TITLE
Transaction fee calculation formula

### ISSUE THREAD

**Issue by artjoma** [OffchainLabs/arbitrum#2407]
How to calculated transaction fee? For example: 
https://arbiscan.io/tx/0x5c7842d8220957c5ba4cdf11a78c03c3363368f9c9d4c50b42f72a3379c0411f

```Transaction Fee: 0.00066567905543 ```

Using code:
```
res, _, _, _, err := s.getTransactionInfoByHash(txHash)
txFee := res.FeeStats.Paid.Total()
```
`return: 665679055437216 `

**Comment by gzeoneth** [comment]
**Note that FeeStats will be removed in nitro in favor of gasPaidL1**
```
      "feeStats": {
            "prices": {
                "l1Transaction": "0x138117eb1d780",
                "l1Calldata": "0x13f8ed7c05",
                "l2Storage": "0x87ae9020cd00",
                "l2Computation": "0x2c75d254"
            },
            "unitsUsed": {
                "l1Transaction": "0x1",
                "l1Calldata": "0xe30",
                "l2Storage": "0x0",
                "l2Computation": "0x399c"
            },
            "paid": {
                "l1Transaction": "0x138117eb1d780",
                "l1Calldata": "0x11b5ba94f86f0",
                "l2Storage": "0x0",
                "l2Computation": "0xa0153a0df30"
            }
        },
```
You can calculate each component paid by multiplying `prices` and `unitsUsed`.
There may be some discrepancy between `Paid.Total()` and `effectiveGasPrice * gasUsed` due to rounding, the number in feeStats is the actual charged transaction fees.
