### ISSUE TITLE
Tracing queries are slow on Arbitrum classic

### ISSUE THREAD

**Issue by klefevre** [OffchainLabs/arbitrum#2546]
Hello everyone, we have some issues to setup properly an Arbitrum classic node to run archive tracing queries on it.
We followed the [documentation](https://developer.arbitrum.io/node-running/running-a-classic-node) and ended running our node (using docker) with the following command:

```
docker run --rm \
	--name arbitrum-classic \
	-v $(pwd)/classic-data:/home/user/.arbitrum/mainnet \
	-p 0.0.0.0:8547:8547 \
	offchainlabs/arb-node:v1.4.5-e97c1a4 \
	--l1.url=<L1-url> \
	--l2.disable-upstream \
	--node.chain-id=42161 \
	--node.rpc.tracing.enable \
	--node.cache.allow-slow-lookup \
	--core.checkpoint-gas-frequency=156250000
```

We then run queries such as `arbtrace_block` like this:

```
time curl http://localhost:8547 \
	-X POST -H "Content-Type: application/json" \
	--data '{"jsonrpc":"2.0","method":"arbtrace_block","params":["'0x(printf "%x" 131)’"], "id":1}'
```

The issue comes from the fact that it takes sometimes ~10sec to compute. We’re kind of surprise of these responses time as such queries on Ethereum takes only milliseconds to process...

We compared those numbers with some node’s providers e.g. QuickNode and we realized that their response times were much better!
We understand that the purpose of Nitro was to improve speed overall, and even if we take into account that node’s providers may cache responses and have probably a load balancer to serve queries, we believe that we might have missed something somewhere...

Does anybody have an idea what parameter(s) we could tweak in order to get better time responses? We tried to remove `--node.cache.allow-slow-lookup` and `--core.checkpoint-gas-frequency=156250000` (as suggested in the documentation) but it doesn't seems to change anything.

**Comment by PlasmaPower** [comment]
Arbitrum classic node speed is highly dependent on disk speed and particularly latency. We'd recommend getting a low latency NVME drive if you want the fastest responses.

**Comment by klefevre** [comment]
That's unfortunate as we already use NVMe drives. There's really nothing else we can do?

**Comment by joshuacolvin0** [comment]
NVMe drives can vary widely in latency.  Make sure you are not using RAID, because that can increase latency as well.  You can use https://github.com/koct9i/ioping to test, you want under 100us latancy, the lower the better.
Also ensure your nodes are not running out of RAM, and the CPU is not being used 100%.  If you are making a lot of simultaneous requests, the CPU and/or RAM can be quickly used up

**Comment by klefevre** [comment]
I tried `ioping` on my laptop and got less than 100 µs (I have a MacBook Pro 2021 which has a NVMe drive btw). On servers we got pretty decent numbers too.

I can't believe that the hard drive is the real and only bottleneck. Even with the fastest hard drive I don't think I'm gonna improve my current ~10s response time to ~100µs as I would expect (actually less than 1s would be ok).

**Comment by joshuacolvin0** [comment]
Classic nodes store machines in a tree, so there is a very large number of sequential database transactions that cannot be parallelized. This is one of the big reasons we switched things around in Nitro.  One thing that does help is if you are walking the chain forward.  As an example, if block 400 is already loaded in cache, then block 401 will load quickly because there is only a small difference that needs to be loaded from database.

**Comment by klefevre** [comment]
That's indeed what we observed. Well if there's nothing more I can do to improve perfs I'll close the ticket. Thanks for clarification.
