### ISSUE TITLE
arb-bridge-eth docker image requires ganache-cli 6.5.0

### ISSUE THREAD

**Issue by hkalodner** [OffchainLabs/arbitrum#3]
Currently we have to pin our version of ganache used for testing in the arb-bridge-eth Dockerfiles to version 6.5.0 rather than allowing it to upgrade due to https://github.com/trufflesuite/ganache-core/issues/467. If this bug is resolved we will be able to upgrade to the latest version of ganache-core and ganache-cli.

**Comment by stefanmendoza** [comment]
Per kumavis's comment on https://github.com/trufflesuite/ganache-core/issues/467 this was fixed in web3-provider-engine@14.2.1 (I'm not seeing a tag for it on GitHub or a commit referencing this version, but it looks like it was published to NPM [here](https://www.npmjs.com/package/web3-provider-engine/v/14.2.1)). The uplift was include in the beta for 2.8.0 of ganache-core ([see here](https://github.com/trufflesuite/ganache-core/compare/v2.7.0...v2.8.0-beta.0)).

**Comment by hkalodner** [comment]
Closing this this is now fixed.
